### ISSUE TITLE
поломка при запуске на устрйостве самсунг гэлэкси с2

### ISSUE THREAD

**Issue by worldwidebaby** [evtn/vk-tweaks#1]
поломка

устройство самсунг
closes #2

**Comment by evtn** [comment]
попробуйте обновить windows с 10 на 8, поможет?
если не получится купите iphone

**Comment by worldwidebaby** [comment]
у меня не оригинал

**Comment by worldwidebaby** [comment]
оригинал

**Comment by evtn** [comment]
спасибо, закрываю
